stages:
  prepare:
    cmd: python3 gpt_snorkel_data_prepare.py
    deps:
    - gpt_snorkel_data_prepare.py
    outs:
    - prepare
  label:
    cmd: python3 gpt_snorkel_label.py label prepare ktrain
    deps:
    - gpt_snorkel_label.py
    - prepare
    outs:
    - label
  label_model:
    cmd: python3 gpt_snorkel_label_model.py snorkel_model label prepare
    deps:
    - gpt_snorkel_label_model.py
    - label
    outs:
    - snorkel_model
